name: YAML Compile Pipeline

on:
  workflow_dispatch:
    inputs:
     yaml:
        description: "Raw YAML content"
        required: true

     target_path:
        description: "Target file path (e.g. .github/workflows/test.yml)"
        required: true

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pyyaml

      - name: Compile YAML
        run: |
          echo "${{ github.event.inputs.yaml }}" | python tools/yaml_compile.py > encoded.txt

      - name: Decode base64 (for save)
        run: |
          base64 -d encoded.txt > output.yaml

      - name: Save to repo
        run: |
          mkdir -p $(dirname "${{ github.event.inputs.target_path }}")
          cp output.yaml "${{ github.event.inputs.target_path }}"

      - name: Commit
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add "${{ github.event.inputs.target_path }}"
          git commit -m "compiled yaml update [skip ci]" || echo "no changes"
          git push